# Generated by Django 3.0.14 on 2022-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0009_auto_20200611_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='backlinks',
            field=jsonfield.fields.JSONField(blank=True, default=list, verbose_name='backlinks'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(verbose_name='note')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Author', verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
